CREATE DATABASE IF NOT EXISTS transversal;
USE transversal;

CREATE TABLE TITULO_PROGRAMA (
  titpro_id INT NOT NULL,
  titpro_nombre VARCHAR(45) NOT NULL,
  PRIMARY KEY (titpro_id)
) ENGINE=InnoDB;

CREATE TABLE PROGRAMA (
  prog_codigo INT NOT NULL,
  prog_denominacion VARCHAR(100) NOT NULL,
  TIT_PROGRAMA_titpro_id INT NOT NULL,
  prog_tipo VARCHAR(30) NOT NULL,
  PRIMARY KEY (prog_codigo),
  CONSTRAINT fk_PROGRAMA_TIPO_PROGRAMA
    FOREIGN KEY (TIT_PROGRAMA_titpro_id)
    REFERENCES TITULO_PROGRAMA (titpro_id)
) ENGINE=InnoDB;

CREATE TABLE COMPETENCIA (
  comp_id INT NOT NULL,
  comp_nombre_corto VARCHAR(30) NOT NULL,
  comp_horas INT NOT NULL,
  comp_nombre_unidad_competencia VARCHAR(150) NOT NULL,
  PRIMARY KEY (comp_id)
) ENGINE=InnoDB;

CREATE TABLE CENTRO_FORMACION (
  cent_id INT NOT NULL,
  cent_nombre VARCHAR(100) NOT NULL,
  PRIMARY KEY (cent_id)
) ENGINE=InnoDB;

CREATE TABLE INSTRUCTOR (
  inst_id INT NOT NULL,
  inst_nombres VARCHAR(45) NOT NULL,
  inst_apellidos VARCHAR(45) NOT NULL,
  inst_correo VARCHAR(45) NOT NULL,
  inst_telefono BIGINT NOT NULL,
  CENTRO_FORMACION_cent_id INT NOT NULL,
  inst_password VARCHAR(45) NOT NULL,
  PRIMARY KEY (inst_id),
  CONSTRAINT fk_INSTRUCTOR_CENTRO_FORMACION1
    FOREIGN KEY (CENTRO_FORMACION_cent_id)
    REFERENCES CENTRO_FORMACION (cent_id)
) ENGINE=InnoDB;

CREATE TABLE COMPETxPROGRAMA (
  PROGRAMA_prog_id INT NOT NULL,
  COMPETENCIA_comp_id INT NOT NULL,
  PRIMARY KEY (PROGRAMA_prog_id, COMPETENCIA_comp_id),
  CONSTRAINT fk_COMPETxPROGRAMA_PROGRAMA1
    FOREIGN KEY (PROGRAMA_prog_id)
    REFERENCES PROGRAMA (prog_codigo),
  CONSTRAINT fk_COMPETxPROGRAMA_COMPETENCIA1
    FOREIGN KEY (COMPETENCIA_comp_id)
    REFERENCES COMPETENCIA (comp_id)
) ENGINE=InnoDB;

CREATE TABLE COORDINACION (
  coord_id INT NOT NULL,
  coord_descripcion VARCHAR(45) NOT NULL,
  CENTRO_FORMACION_cent_id INT NOT NULL,
  coord_nombre_coordinador VARCHAR(45) NOT NULL,
  coord_correo VARCHAR(45) NOT NULL,
  coord_password VARCHAR(45) NOT NULL,
  PRIMARY KEY (coord_id),
  CONSTRAINT fk_COORDINACION_CENTRO_FORMACION1
    FOREIGN KEY (CENTRO_FORMACION_cent_id)
    REFERENCES CENTRO_FORMACION (cent_id)
) ENGINE=InnoDB;

CREATE TABLE FICHA (
  fich_id INT NOT NULL,
  PROGRAMA_prog_id INT NOT NULL,
  INSTRUCTOR_inst_id_lider INT NOT NULL,
  fich_jornada VARCHAR(20) NOT NULL,
  COORDINACION_coord_id INT NOT NULL,
  fich_fecha_ini_lectiva DATE NOT NULL,
  fich_fecha_fin_lectiva DATE NOT NULL,
  PRIMARY KEY (fich_id),
  CONSTRAINT fk_FICHA_PROGRAMA1
    FOREIGN KEY (PROGRAMA_prog_id)
    REFERENCES PROGRAMA (prog_codigo),
  CONSTRAINT fk_FICHA_INSTRUCTOR1
    FOREIGN KEY (INSTRUCTOR_inst_id_lider)
    REFERENCES INSTRUCTOR (inst_id),
  CONSTRAINT fk_FICHA_COORDINACION1
    FOREIGN KEY (COORDINACION_coord_id)
    REFERENCES COORDINACION (coord_id)
) ENGINE=InnoDB;

CREATE TABLE SEDE (
  sede_id INT NOT NULL,
  sede_nombre VARCHAR(45) NOT NULL,
  foto VARCHAR(150),
  PRIMARY KEY (sede_id)
) ENGINE=InnoDB;

CREATE TABLE AMBIENTE (
  amb_id VARCHAR(5) NOT NULL,
  amb_nombre VARCHAR(45),
  SEDE_sede_id INT NOT NULL,
  PRIMARY KEY (amb_id),
  CONSTRAINT fk_AMBIENTE_SEDE1
    FOREIGN KEY (SEDE_sede_id)
    REFERENCES SEDE (sede_id)
) ENGINE=InnoDB;

CREATE TABLE ASIGNACION (
  INSTRUCTOR_inst_id INT NOT NULL,
  asig_fecha_ini DATETIME NOT NULL,
  asig_fecha_fin DATETIME NOT NULL,
  FICHA_fich_id INT NOT NULL,
  AMBIENTE_amb_id VARCHAR(5) NOT NULL,
  COMPETENCIA_comp_id INT NOT NULL,
  ASIG_ID INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (ASIG_ID),
  CONSTRAINT fk_ASIGNACION_INSTRUCTOR1
    FOREIGN KEY (INSTRUCTOR_inst_id)
    REFERENCES INSTRUCTOR (inst_id),
  CONSTRAINT fk_ASIGNACION_FICHA1
    FOREIGN KEY (FICHA_fich_id)
    REFERENCES FICHA (fich_id),
  CONSTRAINT fk_ASIGNACION_AMBIENTE1
    FOREIGN KEY (AMBIENTE_amb_id)
    REFERENCES AMBIENTE (amb_id),
  CONSTRAINT fk_ASIGNACION_COMPETENCIA1
    FOREIGN KEY (COMPETENCIA_comp_id)
    REFERENCES COMPETENCIA (comp_id)
) ENGINE=InnoDB;

CREATE TABLE DETALLExASIGNACION (
  ASIGNACION_ASIG_ID INT NOT NULL,
  detasig_hora_ini DATETIME NOT NULL,
  detasig_hora_fin DATETIME NOT NULL,
  detasig_id INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (detasig_id),
  CONSTRAINT fk_DETALLExASIGNACION_ASIGNACION1
    FOREIGN KEY (ASIGNACION_ASIG_ID)
    REFERENCES ASIGNACION (ASIG_ID)
) ENGINE=InnoDB;

CREATE TABLE INSTRU_COMPETENCIA (
  INSTRUCTOR_inst_id INT NOT NULL,
  COMPETxPROGRAMA_PROGRAMA_prog_id INT NOT NULL,
  COMPETxPROGRAMA_COMPETENCIA_comp_id INT NOT NULL,
  inscomp_vigencia DATE NOT NULL,
  inscomp_id INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (inscomp_id),
  CONSTRAINT fk_INSTRU_COMPETENCIA_INSTRUCTOR1
    FOREIGN KEY (INSTRUCTOR_inst_id)
    REFERENCES INSTRUCTOR (inst_id),
  CONSTRAINT fk_INSTRU_COMPETENCIA_COMPETxPROGRAMA1
    FOREIGN KEY (
      COMPETxPROGRAMA_PROGRAMA_prog_id,
      COMPETxPROGRAMA_COMPETENCIA_comp_id
    )
    REFERENCES COMPETxPROGRAMA (
      PROGRAMA_prog_id,
      COMPETENCIA_comp_id
    )
) ENGINE=InnoDB;
