-- =========================================
-- Script PostgreSQL
-- Base de datos: transversal
-- =========================================

CREATE TABLE TITULO_PROGRAMA (
  titpro_id INT NOT NULL,
  titpro_nombre VARCHAR(255) NOT NULL,
  PRIMARY KEY (titpro_id)
);

CREATE TABLE PROGRAMA (
  prog_codigo INT NOT NULL,
  prog_denominacion VARCHAR(255) NOT NULL,
  TIT_PROGRAMA_titpro_id INT NOT NULL,
  prog_tipo VARCHAR(100) NOT NULL,
  PRIMARY KEY (prog_codigo),
  CONSTRAINT fk_PROGRAMA_TIPO_PROGRAMA
    FOREIGN KEY (TIT_PROGRAMA_titpro_id)
    REFERENCES TITULO_PROGRAMA (titpro_id)
);

CREATE TABLE COMPETENCIA (
  comp_id INT NOT NULL,
  comp_nombre_corto VARCHAR(100) NOT NULL,
  comp_horas INT NOT NULL,
  comp_nombre_unidad_competencia VARCHAR(500) NOT NULL,
  PRIMARY KEY (comp_id)
);

CREATE TABLE CENTRO_FORMACION (
  cent_id INT NOT NULL,
  cent_nombre VARCHAR(255) NOT NULL,
  PRIMARY KEY (cent_id)
);

CREATE TABLE INSTRUCTOR (
  inst_id INT NOT NULL,
  inst_nombres VARCHAR(100) NOT NULL,
  inst_apellidos VARCHAR(100) NOT NULL,
  inst_correo VARCHAR(100) NOT NULL,
  inst_telefono BIGINT NOT NULL,
  CENTRO_FORMACION_cent_id INT NOT NULL,
  inst_password VARCHAR(255) NOT NULL,
  PRIMARY KEY (inst_id),
  CONSTRAINT fk_INSTRUCTOR_CENTRO_FORMACION1
    FOREIGN KEY (CENTRO_FORMACION_cent_id)
    REFERENCES CENTRO_FORMACION (cent_id)
);

CREATE TABLE COMPETxPROGRAMA (
  PROGRAMA_prog_id INT NOT NULL,
  COMPETENCIA_comp_id INT NOT NULL,
  PRIMARY KEY (PROGRAMA_prog_id, COMPETENCIA_comp_id),
  CONSTRAINT fk_COMPETxPROGRAMA_PROGRAMA1
    FOREIGN KEY (PROGRAMA_prog_id)
    REFERENCES PROGRAMA (prog_codigo),
  CONSTRAINT fk_COMPETxPROGRAMA_COMPETENCIA1
    FOREIGN KEY (COMPETENCIA_comp_id)
    REFERENCES COMPETENCIA (comp_id)
);

CREATE TABLE COORDINACION (
  coord_id INT NOT NULL,
  coord_descripcion VARCHAR(255) NOT NULL,
  CENTRO_FORMACION_cent_id INT NOT NULL,
  coord_nombre_coordinador VARCHAR(100) NOT NULL,
  coord_correo VARCHAR(100) NOT NULL,
  coord_password VARCHAR(255) NOT NULL,
  PRIMARY KEY (coord_id),
  CONSTRAINT fk_COORDINACION_CENTRO_FORMACION1
    FOREIGN KEY (CENTRO_FORMACION_cent_id)
    REFERENCES CENTRO_FORMACION (cent_id)
);

CREATE TABLE FICHA (
  fich_id INT NOT NULL,
  PROGRAMA_prog_id INT NOT NULL,
  INSTRUCTOR_inst_id_lider INT NOT NULL,
  fich_jornada VARCHAR(50) NOT NULL,
  COORDINACION_coord_id INT NOT NULL,
  fich_fecha_ini_lectiva DATE NOT NULL,
  fich_fecha_fin_lectiva DATE NOT NULL,
  PRIMARY KEY (fich_id),
  CONSTRAINT fk_FICHA_PROGRAMA1
    FOREIGN KEY (PROGRAMA_prog_id)
    REFERENCES PROGRAMA (prog_codigo),
  CONSTRAINT fk_FICHA_INSTRUCTOR1
    FOREIGN KEY (INSTRUCTOR_inst_id_lider)
    REFERENCES INSTRUCTOR (inst_id),
  CONSTRAINT fk_FICHA_COORDINACION1
    FOREIGN KEY (COORDINACION_coord_id)
    REFERENCES COORDINACION (coord_id)
);

CREATE TABLE SEDE (
  sede_id INT NOT NULL,
  sede_nombre VARCHAR(100) NOT NULL,
  foto VARCHAR(255),
  PRIMARY KEY (sede_id)
);

CREATE TABLE AMBIENTE (
  amb_id VARCHAR(5) NOT NULL,
  amb_nombre VARCHAR(100),
  SEDE_sede_id INT NOT NULL,
  PRIMARY KEY (amb_id),
  CONSTRAINT fk_AMBIENTE_SEDE1
    FOREIGN KEY (SEDE_sede_id)
    REFERENCES SEDE (sede_id)
);

CREATE TABLE ASIGNACION (
  INSTRUCTOR_inst_id INT NOT NULL,
  asig_fecha_ini TIMESTAMP NOT NULL,
  asig_fecha_fin TIMESTAMP NOT NULL,
  FICHA_fich_id INT NOT NULL,
  AMBIENTE_amb_id VARCHAR(5) NOT NULL,
  COMPETENCIA_comp_id INT NOT NULL,
  ASIG_ID SERIAL PRIMARY KEY,
  CONSTRAINT fk_ASIGNACION_INSTRUCTOR1
    FOREIGN KEY (INSTRUCTOR_inst_id)
    REFERENCES INSTRUCTOR (inst_id),
  CONSTRAINT fk_ASIGNACION_FICHA1
    FOREIGN KEY (FICHA_fich_id)
    REFERENCES FICHA (fich_id),
  CONSTRAINT fk_ASIGNACION_AMBIENTE1
    FOREIGN KEY (AMBIENTE_amb_id)
    REFERENCES AMBIENTE (amb_id),
  CONSTRAINT fk_ASIGNACION_COMPETENCIA1
    FOREIGN KEY (COMPETENCIA_comp_id)
    REFERENCES COMPETENCIA (comp_id)
);

CREATE TABLE DETALLExASIGNACION (
  ASIGNACION_ASIG_ID INT NOT NULL,
  detasig_hora_ini TIMESTAMP NOT NULL,
  detasig_hora_fin TIMESTAMP NOT NULL,
  detasig_id SERIAL PRIMARY KEY,
  CONSTRAINT fk_DETALLExASIGNACION_ASIGNACION1
    FOREIGN KEY (ASIGNACION_ASIG_ID)
    REFERENCES ASIGNACION (ASIG_ID)
);

CREATE TABLE INSTRU_COMPETENCIA (
  INSTRUCTOR_inst_id INT NOT NULL,
  COMPETxPROGRAMA_PROGRAMA_prog_id INT NOT NULL,
  COMPETENCIA_comp_id_ref INT NOT NULL, -- Added reference to match logic if needed
  inscomp_vigencia DATE NOT NULL,
  inscomp_id SERIAL PRIMARY KEY,
  CONSTRAINT fk_INSTRU_COMPETENCIA_INSTRUCTOR1
    FOREIGN KEY (INSTRUCTOR_inst_id)
    REFERENCES INSTRUCTOR (inst_id)
);
